dist: xenial

language: go

branches:
  only:
  - master

env:
  global:
  - GO111MODULE=on
  - TEST_DECRYPTER_KEY="projects/sethvargo-gcpkms-test/locations/global/keyRings/test-keyring/cryptoKeys/decrypter/cryptoKeyVersions/1"
  - TEST_SIGNER_KEY="projects/sethvargo-gcpkms-test/locations/global/keyRings/test-keyring/cryptoKeys/signer/cryptoKeyVersions/1"
  - GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_BUILD_DIR}/test/account.json

go:
- 1.13.x

git:
  depth: 1
  quiet: true

install: true

script: make test
